apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml

# Optional: Add namespace if deploying to a specific namespace
# namespace: telegram-bot

# Optional: Add common labels to all resources
commonLabels:
  app.kubernetes.io/name: telegram-bot
  app.kubernetes.io/part-of: telegram-bot

# Optional: Add common annotations to all resources
# commonAnnotations:
#   app.kubernetes.io/managed-by: kustomize