apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secrets
type: Opaque
stringData:
  # These values should be replaced with actual secrets in a real deployment
  # For production, consider using a secret management solution like Vault or Sealed Secrets
  telegram-bot-token: "YOUR_TELEGRAM_BOT_TOKEN"
  llm-api-key: "YOUR_API_KEY"