apiVersion: v1
kind: Service
metadata:
  name: telegram-bot
  labels:
    app: telegram-bot
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: telegram-bot
---
# Optional: If you need to expose the service externally with a stable IP
# Uncomment and configure this Ingress resource
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: telegram-bot
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # Add any other annotations needed for your ingress controller
#     # cert-manager.io/cluster-issuer: letsencrypt-prod
# spec:
#   rules:
#   - host: your-domain.com
#     http:
#       paths:
#       - path: /telegram
#         pathType: Prefix
#         backend:
#           service:
#             name: telegram-bot
#             port:
#               name: http
#   # Uncomment for TLS
#   # tls:
#   # - hosts:
#   #   - your-domain.com
#   #   secretName: telegram-bot-tls